# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 程序员陈师兄
subtitle: ''
description: ''
keywords:
author: 程序员陈师兄
language: zh-CN
timezone: ''





# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://blog.cxycsx.vip
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''


# 首页配置
index:
  slogan:
    enable: true
    text: 个人技术博客
  post_url_target: _blank
  post_meta:
    date: true
    category: true
    tag: true

# 导航栏配置
navbar:
  blog_title: 程序员陈师兄
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    # - { key: "tool", link: "/tools/", icon: "iconfont icon-th-large", name: "工具"}
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }



# 文章配置
post:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: true
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"

# 页面底部
footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
  content: 程序员陈师兄


# 标签云
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


# 友情链接
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  banner_name: 测试
  # 友链的成员项
  # Member item of page
  items:
    - {
      title: "Redis",
      intro: "Redis Windows",
      link: "https://github.com/MicrosoftArchive/redis/releases",
      avatar: "/img/favicon.png"
    }
    - {
      title: "AnotherRedisDesktopManager",
      intro: "Redis 客户端",
      link: "https://github.com/qishibo/AnotherRedisDesktopManager/releases",
      avatar: "/img/favicon.png"
    }
    - {
      title: "utool",
      intro: "utool效率工具",
      link: "https://www.u.tools/",
      avatar: "/img/favicon.png"
    }

    - {
      title: "网盘助手",
      intro: "油猴脚本",
      link: "https://github.com/syhyz1990/baiduyun",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid",
      intro: "Fluid",
      link: "https://hexo.fluid-dev.com/docs/start/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Codeformer",
      intro: "Codeformer",
      link: "https://replicate.com/sczhou/codeformer",
      avatar: "/img/favicon.png"
    }
    - {
      title: "无限邮箱",
      intro: "无限邮箱",
      link: "https://www.2925.com/login/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "测试平台",
      intro: "metersphere",
      link: "https://github.com/metersphere/metersphere",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Clash",
      intro: "Clash",
      link: "https://docs.cfw.lbyczf.com/",
      avatar: "/img/favicon.png"
    }

    - {
      title: "接码平台",
      intro: "接码",
      link: "https://sms-activate.org/",
      avatar: "/img/favicon.png"
    }

    - {
      title: "狗云",
      intro: "狗云",
      link: "https://www.dogyun.com/?ref=cxycsx",
      avatar: "/img/favicon.png"
    }

    - {
      title: "007",
      intro: "007",
      link: "https://www.007idc.cn/aff/ARXNPPNU",
      avatar: "/img/favicon.png"
    }
    - {
      title: "小程序线上日志定位",
      intro: "小程序线上日志定位",
      link: "https://developers.weixin.qq.com/miniprogram/dev/framework/realtimelog/",
      avatar: "/img/favicon.png"
    }



custom_head: '<meta name="referrer" content="no-referrer">'


